name: CI/CD

on:
  push:
  pull_request:
  release:
    types:
      - published

jobs:

  build_sdist:
    name: Build source distribution 
    runs-on: ubuntu-22.04
    permissions:
      id-token: write
    strategy:
      matrix:
        python-version:
          - '3.10'

    steps:

      - uses: actions/checkout@master
      - run: git fetch --prune --unshallow

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install basic tools
        run: pip install setuptools_scm build

      - name: Build sdist
        run: python -m build --sdist

      - name: Install sdist
        run: pip -v install dist/*.tar.gz

      - name: Test import
        run: python -c 'import gym_gz_models; print(gym_gz_models.get_model_file("ground_plane"))'

      - uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist/*.tar.gz

  build_wheels:
    name: Build wheels
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - '3.10'
    
    steps:

      - uses: actions/checkout@master
      - run: git fetch --prune --unshallow

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install cibuildwheel
        run: pip install cibuildwheel

      - name: Build wheels
        run: |
          python -m cibuildwheel --output-dir wheelhouse
          echo ""
          echo "Distributions:"
          ls -alh wheelhouse/
        env:
          CIBW_BUILD_VERBOSITY: 1
          CIBW_BUILD: cp310-*manylinux*_x86_64
          CIBW_MANYLINUX_X86_64_IMAGE: manylinux_2_28
          CIBW_ENVIRONMENT_LINUX: AUDITWHEEL_PLAT=manylinux_2_28_x86_64
          CIBW_TEST_COMMAND: "python -c 'import gym_gz_models; print(gym_gz_models.get_model_file(\"ground_plane\"))'"

      - uses: actions/upload-artifact@v3
        with:
          name: dist
          path: ./wheelhouse/*.whl
    
  upload_pypi:
    needs:
      - build_sdist
      - build_wheels
    runs-on: ubuntu-22.04
    permissions:
      id-token: write

    steps:
      - uses: actions/download-artifact@v3
        with:
          name: dist
          path: dist

      - name: Inspect dist folder
        run: ls -lah dist/
        
      - name: Publish to PyPI
        if: |
          github.repository == 'andreaostuni/gym-gz-models' &&
          ((github.event_name == 'release' && github.event.action == 'published') ||
           (github.event_name == 'push' && github.ref == 'refs/heads/master'))
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          skip-existing: true
