name: CI/CD

on:
  push:
  pull_request:
  release:
    types:
      - published

jobs:

  build-n-publish:
    name: Python Packaging
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version:
          - '3.10'

    steps:

      - uses: actions/checkout@master
      - run: git fetch --prune --unshallow

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install basic tools
        run: pip install setuptools_scm

      - name: Create distributions
        run: |
          python setup.py sdist
          pip wheel -w dist/ .
          echo ""
          echo "Distributions:"
          ls -alh dist/

      - name: Rename wheel
        run: |
          sudo apt update
          sudo apt install rename
          find . -type f -name "*.whl" -exec rename -v "s/cp(\d)(\d)-cp(\d)(\d)-linux_x86_64/py3-none-any/g" {} +

      - name: Publish to PyPI
        if: |
          github.repository == 'andreaostuni/gym-gz-models' &&
          ((github.event_name == 'release' && github.event.action == 'published') ||
           (github.event_name == 'push' && github.ref == 'refs/heads/master'))
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          password: ${{ secrets.PYPI_TOKEN }}
          skip-existing: true
